# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Download Z3
        uses: pavpanchekha/setup-z3@0.2.0
        with:
          version: '4.8.15'
          architecture: 'x64'
          distribution: 'glibc-2.31'
      - name: Setup Z3
        run: |
          cp $CPATH/../bin/com.microsoft.z3.jar $GITHUB_WORKSPACE/lib/com.microsoft.z3.jar
          sudo cp $CPATH/../bin/*.so  /lib
      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@0.0.6
        with:
          # version of Ghidra
          version: '10.1.2'
      - name: Unit test
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          gradle-version: current
          arguments: test
